version: "3.2"

services:
  essim:
    image: ci.tno.nl/essim/open-sourced-essim/essim-engine:latest
    ports:
     - 8112:8112
    environment:
     - HTTP_SERVER_SCHEME=http
     - HTTP_SERVER_HOSTNAME=0.0.0.0
     - HTTP_SERVER_PORT=8112
     - HTTP_SERVER_PATH=essim
     - MONGODB_HOST=mongo
     - MONGODB_PORT=27017
     - GRAFANA_ADMIN_USER=admin
     - GRAFANA_ADMIN_PASSWORD=admin
     - GRAFANA_INTERNAL_URL=http://grafana:3000
     - GRAFANA_EXTERNAL_URL=http://localhost:3000
     - CONSOLE_LOG_LEVEL=debug
     - EMISSION_MANAGER_ENABLE=false
     - FILE_LOG_LEVEL=debug
     - LOG_FILE_LOCATION=logs
     - LOG_FILES_SIZE_CAP=2GB
     - MAX_LOG_FILE_SIZE=10MB
     - MAX_LOG_HISTORY_DAYS=60
     - PROFILE_QUERY_TIMEOUT=120
    depends_on:
     - mongo
     - influxdb
    networks:
     - mmvib-net

  nats:
    image: ci.tno.nl/essim/modified-nats/nats-server:latest
    ports:
     - 4222:4222
     - 8222:8222
     - 6222:6222
    networks:
     - mmvib-net

  mongo:
    image: mvertes/alpine-mongo
    ports:
      - 0.0.0.0:27017:27017
    volumes:
      - mongo-storage:/data/db
    networks:
     - mmvib-net

  influxdb:
    image: influxdb:1.7
    ports:
      - 8086:8086
      - 8998:8088
    volumes:
      - influxdb-storage:/var/lib/influxdb
    networks:
     - mmvib-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
     - mmvib-net

  total-energy-production:
    image: ci.tno.nl/essim/kpi-modules/kpi-modules/total-energy-production:latest
    depends_on:
     - mongo
     - nats
    networks:
     - mmvib-net

volumes:
  grafana-storage:
  influxdb-storage:
  mongo-storage:

networks:
  mmvib-net:
    external: true
